/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ama.opengov.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the emailContact service. Represents a row in the &quot;email_contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ama.opengov.model.impl.emailContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ama.opengov.model.impl.emailContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see emailContact
 * @see ama.opengov.model.impl.emailContactImpl
 * @see ama.opengov.model.impl.emailContactModelImpl
 * @generated
 */
@ProviderType
public interface emailContactModel extends BaseModel<emailContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a email contact model instance should use the {@link emailContact} interface instead.
	 */

	/**
	 * Returns the primary key of this email contact.
	 *
	 * @return the primary key of this email contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this email contact.
	 *
	 * @param primaryKey the primary key of this email contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this email contact.
	 *
	 * @return the uuid of this email contact
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this email contact.
	 *
	 * @param uuid the uuid of this email contact
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this email contact.
	 *
	 * @return the ID of this email contact
	 */
	public long getId();

	/**
	 * Sets the ID of this email contact.
	 *
	 * @param id the ID of this email contact
	 */
	public void setId(long id);

	/**
	 * Returns the nome of this email contact.
	 *
	 * @return the nome of this email contact
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this email contact.
	 *
	 * @param nome the nome of this email contact
	 */
	public void setNome(String nome);

	/**
	 * Returns the email of this email contact.
	 *
	 * @return the email of this email contact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this email contact.
	 *
	 * @param email the email of this email contact
	 */
	public void setEmail(String email);

	/**
	 * Returns the mensagem of this email contact.
	 *
	 * @return the mensagem of this email contact
	 */
	@AutoEscape
	public String getMensagem();

	/**
	 * Sets the mensagem of this email contact.
	 *
	 * @param mensagem the mensagem of this email contact
	 */
	public void setMensagem(String mensagem);

	/**
	 * Returns the status of this email contact.
	 *
	 * @return the status of this email contact
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this email contact is status.
	 *
	 * @return <code>true</code> if this email contact is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this email contact is status.
	 *
	 * @param status the status of this email contact
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ama.opengov.model.emailContact emailContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ama.opengov.model.emailContact> toCacheModel();

	@Override
	public ama.opengov.model.emailContact toEscapedModel();

	@Override
	public ama.opengov.model.emailContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}