/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pt.ama.service.db.entities.model.impl;

import aQute.bnd.annotation.ProviderType;

import pt.ama.service.db.entities.model.UserPersonalData;
import pt.ama.service.db.entities.service.UserPersonalDataLocalServiceUtil;

/**
 * The extended model base implementation for the UserPersonalData service. Represents a row in the &quot;ogp_UserPersonalData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserPersonalDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPersonalDataImpl
 * @see UserPersonalData
 * @generated
 */
@ProviderType
public abstract class UserPersonalDataBaseImpl extends UserPersonalDataModelImpl
	implements UserPersonalData {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user personal data model instance should use the {@link UserPersonalData} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserPersonalDataLocalServiceUtil.addUserPersonalData(this);
		}
		else {
			UserPersonalDataLocalServiceUtil.updateUserPersonalData(this);
		}
	}
}