/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package AMA.OpenGov.LocalDataSaveEmail.model.impl;

import AMA.OpenGov.LocalDataSaveEmail.model.ogp_comments;
import AMA.OpenGov.LocalDataSaveEmail.service.ogp_commentsLocalServiceUtil;

import aQute.bnd.annotation.ProviderType;

/**
 * The extended model base implementation for the ogp_comments service. Represents a row in the &quot;AMA_ogp_comments&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ogp_commentsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ogp_commentsImpl
 * @see ogp_comments
 * @generated
 */
@ProviderType
public abstract class ogp_commentsBaseImpl extends ogp_commentsModelImpl
	implements ogp_comments {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ogp_comments model instance should use the {@link ogp_comments} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ogp_commentsLocalServiceUtil.addogp_comments(this);
		}
		else {
			ogp_commentsLocalServiceUtil.updateogp_comments(this);
		}
	}
}