/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pt.ama.service.db.entities.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserPersonalData service. Represents a row in the &quot;ogp_UserPersonalData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link pt.ama.service.db.entities.model.impl.UserPersonalDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link pt.ama.service.db.entities.model.impl.UserPersonalDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPersonalData
 * @see pt.ama.service.db.entities.model.impl.UserPersonalDataImpl
 * @see pt.ama.service.db.entities.model.impl.UserPersonalDataModelImpl
 * @generated
 */
@ProviderType
public interface UserPersonalDataModel extends BaseModel<UserPersonalData>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user personal data model instance should use the {@link UserPersonalData} interface instead.
	 */

	/**
	 * Returns the primary key of this user personal data.
	 *
	 * @return the primary key of this user personal data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user personal data.
	 *
	 * @param primaryKey the primary key of this user personal data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user personal data.
	 *
	 * @return the user ID of this user personal data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user personal data.
	 *
	 * @param userId the user ID of this user personal data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user personal data.
	 *
	 * @return the user uuid of this user personal data
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user personal data.
	 *
	 * @param userUuid the user uuid of this user personal data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this user personal data.
	 *
	 * @return the company ID of this user personal data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user personal data.
	 *
	 * @param companyId the company ID of this user personal data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the identification ID of this user personal data.
	 *
	 * @return the identification ID of this user personal data
	 */
	@AutoEscape
	public String getIdentificationId();

	/**
	 * Sets the identification ID of this user personal data.
	 *
	 * @param identificationId the identification ID of this user personal data
	 */
	public void setIdentificationId(String identificationId);

	/**
	 * Returns the lawer ID of this user personal data.
	 *
	 * @return the lawer ID of this user personal data
	 */
	@AutoEscape
	public String getLawerId();

	/**
	 * Sets the lawer ID of this user personal data.
	 *
	 * @param lawerId the lawer ID of this user personal data
	 */
	public void setLawerId(String lawerId);

	/**
	 * Returns the solicitor ID of this user personal data.
	 *
	 * @return the solicitor ID of this user personal data
	 */
	@AutoEscape
	public String getSolicitorId();

	/**
	 * Sets the solicitor ID of this user personal data.
	 *
	 * @param solicitorId the solicitor ID of this user personal data
	 */
	public void setSolicitorId(String solicitorId);

	/**
	 * Returns the notary ID of this user personal data.
	 *
	 * @return the notary ID of this user personal data
	 */
	@AutoEscape
	public String getNotaryId();

	/**
	 * Sets the notary ID of this user personal data.
	 *
	 * @param notaryId the notary ID of this user personal data
	 */
	public void setNotaryId(String notaryId);

	/**
	 * Returns the passport ID of this user personal data.
	 *
	 * @return the passport ID of this user personal data
	 */
	@AutoEscape
	public String getPassportId();

	/**
	 * Sets the passport ID of this user personal data.
	 *
	 * @param passportId the passport ID of this user personal data
	 */
	public void setPassportId(String passportId);

	/**
	 * Returns the nationality of this user personal data.
	 *
	 * @return the nationality of this user personal data
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this user personal data.
	 *
	 * @param nationality the nationality of this user personal data
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the authentication type of this user personal data.
	 *
	 * @return the authentication type of this user personal data
	 */
	@AutoEscape
	public String getAuthenticationType();

	/**
	 * Sets the authentication type of this user personal data.
	 *
	 * @param authenticationType the authentication type of this user personal data
	 */
	public void setAuthenticationType(String authenticationType);

	/**
	 * Returns the agree full name of this user personal data.
	 *
	 * @return the agree full name of this user personal data
	 */
	@AutoEscape
	public String getAgreeFullName();

	/**
	 * Sets the agree full name of this user personal data.
	 *
	 * @param agreeFullName the agree full name of this user personal data
	 */
	public void setAgreeFullName(String agreeFullName);

	/**
	 * Returns the agree portal use data of this user personal data.
	 *
	 * @return the agree portal use data of this user personal data
	 */
	@AutoEscape
	public String getAgreePortalUseData();

	/**
	 * Sets the agree portal use data of this user personal data.
	 *
	 * @param agreePortalUseData the agree portal use data of this user personal data
	 */
	public void setAgreePortalUseData(String agreePortalUseData);

	/**
	 * Returns the agree email of this user personal data.
	 *
	 * @return the agree email of this user personal data
	 */
	@AutoEscape
	public String getAgreeEmail();

	/**
	 * Sets the agree email of this user personal data.
	 *
	 * @param agreeEmail the agree email of this user personal data
	 */
	public void setAgreeEmail(String agreeEmail);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		pt.ama.service.db.entities.model.UserPersonalData userPersonalData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<pt.ama.service.db.entities.model.UserPersonalData> toCacheModel();

	@Override
	public pt.ama.service.db.entities.model.UserPersonalData toEscapedModel();

	@Override
	public pt.ama.service.db.entities.model.UserPersonalData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}